# name: Deploy to Test Server

# on:
#   push:
#     branches:
#       - main

# concurrency:
#   group: deploy-main
#   cancel-in-progress: false

# jobs:

#   deploy:
#     name: Deploy to Main
#     runs-on: self-hosted
#     environment: main
#     timeout-minutes: 15

#     permissions:
#       contents: read

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Add SSH key
#         uses: webfactory/ssh-agent@v0.10.0
#         with:
#           ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

#       - name: Add server to known_hosts
#         run: ssh-keyscan -H ${{ secrets.TEST_SSH_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy via SSH
#         run: |

#           ssh ${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_SSH_HOST }} bash -s << 'ENDSSH'
#             set -e
#             cd /var/www/testcrm.umram.online/crm-be
#             trap 'go version 2>/dev/null || true' EXIT

#             git pull origin main
#             go mod download
#             go build -o app ./cmd/api/main.go
#             chmod +x app
#             ./app
#             trap - EXIT

#             echo "Test deployment complete"
#           ENDSSH